algoritmo "Calculadora"
var
    n1: inteiro
    n2: inteiro
    s: inteiro
    nome: caractere
inicio
    escreval("Bom Dia")
    escreva("Qual é o seu nome?")
    leia(nome)
    escreval("Muito Prazer ", nome)
    escreva(nome, " diga-me um número: ")
    leia(n1)
    escreva(nome, " diga-me outro número: ")
    leia(n2)
    s <- n1 + n2    escreva("A soma de ", n1, " + ", n2)
    escreval(s)
    escreva("Obrigado por participar ")
    escreva(nome)

fimalgoritmo